// <auto-generated />
using System;
using Infrastructure.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Storage.Migrations
{
    [DbContext(typeof(MassiveDelDbContext))]
    partial class MassiveDelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Infrastructure.Storage.Models.UserListElement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserListInfoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserListInfoId");

                    b.ToTable("UserListElements");
                });

            modelBuilder.Entity("Infrastructure.Storage.Models.UserListInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActiveContext")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChatId", "Name")
                        .IsUnique();

                    b.ToTable("UserListInfos");
                });

            modelBuilder.Entity("Infrastructure.Storage.Models.UserListElement", b =>
                {
                    b.HasOne("Infrastructure.Storage.Models.UserListInfo", "UserListInfo")
                        .WithMany("UserListElements")
                        .HasForeignKey("UserListInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserListInfo");
                });

            modelBuilder.Entity("Infrastructure.Storage.Models.UserListInfo", b =>
                {
                    b.Navigation("UserListElements");
                });
#pragma warning restore 612, 618
        }
    }
}
